Fastlane-CD #3
elpassion/el-space-ios pull request #18
Opened 2017-06-02 15:30 UTC by bartguminiak

2017-06-03 01:02 UTC, sxcore requested changes
We will talk about my concerns first thing in the morning on Monday. Besides that, everything looks really good and legit 🥇

2017-06-03 01:02 UTC, Drwalcore commented on ELSpace.xcodeproj/project.pbxproj
> +				CODE_SIGN_IDENTITY = "iPhone Developer: Dariusz Rybicki (KB57E8RV46)";
Are You sure that we should share this information in **Public Repository**?

2017-06-03 01:02 UTC, Drwalcore commented on ELSpace.xcodeproj/project.pbxproj
> +				CODE_SIGN_IDENTITY = "iPhone Developer: Dariusz Rybicki (KB57E8RV46)";
Are You sure that we should share this information in **Public Repository**?

2017-06-03 01:02 UTC, Drwalcore commented on fastlane/Fastfile
> +    # This block is called, only if the executed lane was successful
I think It would be cool to send message to our Slack with successful lane?

2017-06-05 10:33 UTC, bartguminiak commented on fastlane/Fastfile
> +    # This block is called, only if the executed lane was successful
:+1: I will add it as new feature

2017-06-05 10:35 UTC, merged